// 1......Creating a Hash

//👉🏻 Hashing is a one-way transformation of data into a fixed-length string of characters.

// 📌 Hash functions have several important properties:
//    🔸 Deterministic: Same input always produces the same output
//    🔸 Fixed Length: Output is always the same size regardless of input size
//    🔸 One-Way: Extremely difficult to reverse the process
//    🔸 Avalanche Effect: Small changes in input produce significant changes in output

// 📌 Common use cases include:
//    🔸 Password storage
//    🔸 Data integrity verification
//    🔸 Digital signatures
//    🔸 Content addressing (e.g., Git, IPFS)



const crypto = require('crypto')

// Create a Hash object
const hash = crypto.createHash('sha256')
console.log(hash) //no use.

// Update the Hash with data
const update = hash.update('Hello')
console.log(update) //no use.

// Get the Digest in hexaadecimal format
const digest = hash.digest('hex')
console.log(digest) //display the hash✅.

// In this example:
//     createHash(): creates a hash object with the specified algorithm
//     update(): updates the hash content with the given data
//     digest(): calculates the digest and outputs it in the specified format

//digest definition: a digest (or message digest, hash, hash value) is a fixed-size, unique "fingerprint" of a message or data, generated by a cryptographic hash function.